import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid, Legend } from 'recharts';
import { counts, statusLabel, statuses } from '../../utils/metrics';
import type { Dataset, Status } from '../../types';
const colors:Record<Status,string>={open:'#c7404d',closed:'#176caa',resolved:'#16815d',cancelled:'#7e8794',retest:'#ad6a00'};
export function StatusDonut({items,label}:{items:{status:Status}[];label:string}){const c=counts(items),total=items.length;const data=statuses.map(status=>({name:statusLabel[status],value:c[status],status}));return <div className="donut-wrap"><div className="donut" role="img" aria-label={`${label}: ${total} no total. ${data.map(x=>`${x.value} ${x.name.toLowerCase()}`).join(', ')}`}><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={63} outerRadius={83} stroke="none">{data.map(x=><Cell key={x.status} fill={colors[x.status]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{total}</strong><span>no total</span></div></div><ul className="chart-legend">{data.map(x=><li key={x.status}><span className="legend-dot" style={{background:colors[x.status]}}/><span>{x.name}</span><strong>{x.value}</strong><small>{total?Math.round(x.value/total*100):0}%</small></li>)}</ul></div>}
export function EvolutionChart({data,kind}:{data:Dataset;kind:'issues'|'regressionTests'}){const rows:Record<string,string|number>[]=data.versions.map(v=>{const c=counts(data[kind].filter(x=>x.versionId===v.id));return {version:v.name,...Object.fromEntries(statuses.map(status=>[statusLabel[status],c[status]]))};});return <div><div className="chart-area" role="img" aria-label={`Evolução de ${kind==='issues'?'bugs de acessibilidade':'testes regressivos'} por versão`}><ResponsiveContainer width="100%" height={270}><BarChart data={rows} margin={{top:12,right:10,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="version"/><YAxis allowDecimals={false}/><Tooltip/><Legend/>{statuses.map(status=><Bar key={status} dataKey={statusLabel[status]} fill={colors[status]} radius={[3,3,0,0]}/>)}</BarChart></ResponsiveContainer></div><details className="chart-data"><summary>Ver dados do gráfico em tabela</summary><div className="table-scroll"><table><thead><tr><th>Versão</th>{statuses.map(s=><th key={s}>{statusLabel[s]}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.version}><th scope="row">{r.version}</th>{statuses.map(s=><td key={s}>{r[statusLabel[s]]}</td>)}</tr>)}</tbody></table></div></details></div>}
export function StatusBadge({status}:{status:Status|string}){return <span className={`badge badge-${status}`}>{status in statusLabel?statusLabel[status as Status]:status}</span>}

export function ScopeChart({data}:{data:Dataset}){const rows=data.versions.map(version=>{const linked=data.issues.filter(issue=>(version.scopeIssueIds||[]).includes(issue.id)),corrected=linked.filter(issue=>issue.status==='resolved'||issue.status==='closed').length,pending=linked.length-corrected,unlinked=Math.max(version.scenarios-linked.length,0);return {version:version.name,Corrigidos:corrected,Pendentes:pending,'Não vinculados':unlinked};});return <div><div className="chart-area" role="img" aria-label="Situação dos itens do escopo por versão"><ResponsiveContainer width="100%" height={270}><BarChart data={rows} margin={{top:12,right:10,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="version"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="Corrigidos" stackId="scope" fill="#16815d"/><Bar dataKey="Pendentes" stackId="scope" fill="#ad6a00"/><Bar dataKey="Não vinculados" stackId="scope" fill="#7e8794"/></BarChart></ResponsiveContainer></div><details className="chart-data"><summary>Ver dados do escopo em tabela</summary><div className="table-scroll"><table><thead><tr><th>Versão</th><th>Corrigidos</th><th>Pendentes</th><th>Não vinculados</th></tr></thead><tbody>{rows.map(row=><tr key={row.version}><th scope="row">{row.version}</th><td>{row.Corrigidos}</td><td>{row.Pendentes}</td><td>{row['Não vinculados']}</td></tr>)}</tbody></table></div></details></div>}
