import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useApp } from '../contexts/AppContext';
import { Empty, Field } from '../components/ui/Fields';
import { EvolutionChart } from '../components/charts/Charts';
import { counts, dateBR } from '../utils/metrics';
import accessibilityLogo from '../assets/accessibility-logo.svg';
export function Knowledge(){const {data}=useApp();const [q,setQ]=useState('');if(!data)return <p>Carregando...</p>;const articles=data.knowledgeArticles.filter(x=>`${x.title} ${x.problem} ${x.impact}`.toLowerCase().includes(q.toLowerCase()));return <div className="page-stack"><div className="section-title"><div><span className="eyebrow">CONSULTA</span><h2>Base de conhecimento</h2><p>Orientações práticas para identificar e corrigir barreiras.</p></div></div><div className="card"><Field label="Pesquisar artigos"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Busque por problema ou orientação"/></Field></div><div className="knowledge-grid">{articles.map(a=><article className="card" key={a.id}><span className="eyebrow">GUIA DE ACESSIBILIDADE</span><h3>{a.title}</h3><p>{a.impact}</p><details><summary>Ler orientação</summary><dl className="article-details"><dt>Problema</dt><dd>{a.problem}</dd><dt>Impacto</dt><dd>{a.impact}</dd><dt>Como identificar</dt><dd>{a.identify}</dd><dt>Como testar</dt><dd>{a.test}</dd><dt>Comportamento esperado</dt><dd>{a.expected}</dd><dt>Exemplo</dt><dd>{a.example}</dd></dl><strong>Ocorrências relacionadas</strong><ul>{a.related.map(id=><li key={id}><Link to={`/issues/${id}`}>{data.issues.find(x=>x.id===id)?.jiraKey||id}</Link></li>)}</ul></details></article>)}</div>{!articles.length&&<Empty>Nenhum artigo encontrado.</Empty>}</div>}
const steps=['Bug identificado','Análise de acessibilidade','Definição do escopo','Testes','Apontamentos','Correções','Reteste','Regressivo','Aprovação da versão'];
export function Process(){return <div className="page-stack"><div className="section-title"><div><span className="eyebrow">COMO TRABALHAMOS</span><h2>Processo e equipe</h2><p>Etapas e responsabilidades da validação.</p></div></div><section className="card"><h3>Fluxo de validação</h3><ol className="process-list">{steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong></li>)}</ol></section><section className="card"><h3>Equipe de validação</h3><div className="role-grid"><article><h4>Analistas de acessibilidade</h4><p>Testam jornadas com tecnologias assistivas e registram barreiras reais de uso.</p></article><article><h4>Desenvolvimento</h4><p>Realiza correções e acompanha os apontamentos.</p></article><article><h4>Governança e operação</h4><p>Acompanha a evolução e decide sobre a aprovação operacional da versão.</p></article></div></section></div>}
export function Analytics(){const {data}=useApp();if(!data)return <p>Carregando...</p>;const c=counts(data.issues),byJourney=Object.entries(data.issues.reduce<Record<string,number>>((a,x)=>(a[x.journey]=(a[x.journey]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);const byComponent=Object.entries(data.issues.reduce<Record<string,number>>((a,x)=>(a[x.component]=(a[x.component]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);const metrics=[['Total de barreiras',data.issues.length],['Android',data.issues.filter(x=>x.platform==='Android'||x.platform==='Ambos').length],['iOS',data.issues.filter(x=>x.platform==='iOS'||x.platform==='Ambos').length],['Abertos',c.open],['Resolvidos',c.resolved],['Fechados',c.closed],['Cancelados',c.cancelled],['Aguardando reteste',c.retest],['Recorrências',data.issues.filter(x=>data.issues.some(y=>y.id!==x.id&&y.title===x.title)).length],['Tempo médio de resolução','Sem dados']];return <div className="page-stack"><div className="section-title"><div><span className="eyebrow">DADOS</span><h2>Indicadores</h2><p>Indicadores calculados a partir dos registros disponíveis.</p></div></div><div className="metric-grid">{metrics.map(([label,value])=><div className="card metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><section className="card"><h3>Barreiras por versão e status</h3><p>Valores absolutos por versão. A tabela abaixo do gráfico oferece os mesmos números em texto.</p><EvolutionChart data={data} kind="issues"/></section><div className="cards-two"><section className="card"><h3>Jornadas com mais apontamentos</h3><ol className="rank-list">{byJourney.map(([name,n])=><li key={name}><span>{name}</span><strong>{n}</strong></li>)}</ol></section><section className="card"><h3>Componentes com mais apontamentos</h3><ol className="rank-list">{byComponent.map(([name,n])=><li key={name}><span>{name}</span><strong>{n}</strong></li>)}</ol></section></div></div>}
export function Reports(){const {data}=useApp();const [version,setVersion]=useState('8.42.0');if(!data)return <p>Carregando...</p>;const v=data.versions.find(x=>x.id===version),issues=data.issues.filter(x=>x.versionId===version),reg=data.regressionTests.filter(x=>x.versionId===version),c=counts(issues);return <div className="page-stack"><div className="section-title"><div><span className="eyebrow">EXPORTAÇÃO</span><h2>Relatórios</h2><p>Resumo de validação pronto para impressão.</p></div><button className="primary no-print" onClick={()=>window.print()}>Imprimir relatório</button></div><div className="card no-print"><Field label="Selecionar versão"><select value={version} onChange={e=>setVersion(e.target.value)}>{data.versions.map(x=><option key={x.id}>{x.id}</option>)}</select></Field></div><article className="card report"><span className="eyebrow">RELATÓRIO DE QUALIDADE</span><h3>Versão {version}</h3><p>Período iniciado em {dateBR(v?.date||'')} · Gerado em {new Date().toLocaleDateString('pt-BR')}</p><dl className="report-grid">{[['Apontamentos',issues.length],['Resolvidos',c.resolved],['Abertos',c.open],['Fechados',c.closed],['Cancelados',c.cancelled],['Aguardando reteste',c.retest],['Android',issues.filter(x=>x.platform==='Android'||x.platform==='Ambos').length],['iOS',issues.filter(x=>x.platform==='iOS'||x.platform==='Ambos').length],['Cenários regressivos',reg.reduce((n,x)=>n+x.scenarios,0)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="report-foot">Resumo gerado automaticamente a partir dos registros disponíveis no painel.</p></article></div>}
export function Login(){
  const {login,register,logout,demo,profile,authenticated}=useApp();
  const [mode,setMode]=useState<'login'|'register'>('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
  let content;
  if(demo){content=<div className="auth-warning" role="status"><strong>Nenhuma conta está conectada.</strong><p>Este ambiente não possui as variáveis do Firebase. Você está vendo dados fictícios somente para consulta.</p></div>}
  else if(profile?.role==='pending'){content=<div className="auth-warning" role="status"><strong>Cadastro aguardando aprovação.</strong><p>Um administrador precisa aprovar seu acesso. Conta: {profile.email}</p><button className="secondary" onClick={()=>void logout()}>Sair</button></div>}
  else if(profile?.role==='blocked'){content=<div className="auth-warning" role="alert"><strong>Acesso bloqueado.</strong><p>Procure o administrador responsável pelo painel.</p><button className="secondary" onClick={()=>void logout()}>Sair</button></div>}
  else if(profile){content=<div className="session-card"><span className="session-status"><span aria-hidden="true"/>Conectado</span><p><strong>{profile.name}</strong><br/>{profile.email}<br/>Perfil: {profile.role==='admin'?'Administrador':profile.role==='editor'?'Editor':'Somente leitura'}</p><div className="actions"><Link className="primary button-link" to="/">Ir para o painel</Link><button className="secondary" onClick={()=>void logout()}>Sair da conta</button></div></div>}
  else if(mode==='register'){content=<form onSubmit={async e=>{e.preventDefault();try{setError('');await register(name,email,password);}catch{setError('Não foi possível cadastrar. Confira os dados ou tente outro email.')}}}><Field label="Nome"><input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Email"><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Senha (mínimo 6 caracteres)"><input type="password" minLength={6} autoComplete="new-password" required value={password} onChange={e=>setPassword(e.target.value)}/></Field><button className="primary">Solicitar cadastro</button><button type="button" className="text-btn" onClick={()=>{setMode('login');setError('')}}>Já tenho conta</button>{error&&<p role="alert">{error}</p>}</form>}
  else{content=<form onSubmit={async e=>{e.preventDefault();try{setError('');await login(email,password);}catch{setError('Não foi possível entrar. Verifique email e senha.')}}}><Field label="Email"><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Senha"><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></Field><button className="primary">Entrar</button><button type="button" className="text-btn" onClick={()=>{setMode('register');setError('')}}>Solicitar acesso</button>{error&&<p role="alert">{error}</p>}</form>}
  return <div className="login-page"><div className="card login-card"><img className="login-logo" src={accessibilityLogo} alt="Símbolo internacional de acessibilidade"/><Link to="/" className="inline-link">← Voltar ao painel</Link><span className="eyebrow">ACESSO À EQUIPE</span><h2>{authenticated?(profile?.role==='pending'?'Aguardando aprovação':'Conta conectada'):mode==='register'?'Solicitar acesso':'Entrar'}</h2>{content}</div></div>;
}
